<?xml version="1.0"?>
<robot name="diffbot2"
  xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:arg name="base_width" default="0.3"/>
  <xacro:property name="base_length" default="0.4"/>
  <xacro:property name="base_height" default="0.08"/>

  <xacro:property name="wheel_radius" default="0.05"/>
  <xacro:property name="wheel_thickness" default="0.1"/>

  <!-- Include macros -->
  <xacro:include filename="$(find diffbot2_description)/urdf/wheel.xacro"/>

  <!-- Base -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${base_length} $(arg base_width) ${base_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${base_length} $(arg base_width) ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Wheels -->
  <xacro:wheel name="left_wheel" parent="base_link" radius="${wheel_radius}" thickness="${wheel_thickness}">
    <origin xyz="0 ${$(arg base_width)/2 + wheel_thickness/2} 0" rpy="${-pi/2.} 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="right_wheel" parent="base_link" radius="${wheel_radius}" thickness="${wheel_thickness}">
    <origin xyz="0 ${-$(arg base_width)/2. - wheel_thickness/2.} 0" rpy="${pi/2.} 0 0"/>
  </xacro:wheel>

</robot>
