<?xml version="1.0"?>
<robot name="diffbot2"
  xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Arguments -->
  <xacro:arg name="base_width" default="0.5"/>
  <xacro:arg name="base_length" default="0.8"/>
  <xacro:arg name="base_height" default="0.2"/>

  <xacro:arg name="wheel_radius" default="0.2"/>
  <xacro:arg name="wheel_thickness" default="0.1"/>

  <!-- Include macros -->
  <xacro:include filename="$(find diffbot2_description)/urdf/wheel.xacro"/>

  <!-- Base -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5"/>
      <inertia ixx="5" ixy="0" ixz="0" iyy="5" iyz="0" izz="5"/>
    </inertial>
    <visual>
      <geometry>
        <box size="$(arg base_length) $(arg base_width) $(arg base_height)"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="$(arg base_length) $(arg base_width) $(arg base_height)"/>
      </geometry>
    </collision>
  </link>

  <!-- Wheels -->
  <xacro:wheel name="left_wheel" parent="base_link" radius="$(arg wheel_radius)" thickness="$(arg wheel_thickness)">
    <origin xyz="0 ${$(arg base_width)/2 + $(arg wheel_thickness)/2} 0" rpy="${-pi/2.} 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="right_wheel" parent="base_link" radius="$(arg wheel_radius)" thickness="$(arg wheel_thickness)">
    <origin xyz="0 ${-$(arg base_width)/2. - $(arg wheel_thickness)/2.} 0" rpy="${pi/2.} 0 0"/>
  </xacro:wheel>

</robot>
