name: Colcon build and test

on: [pull_request]

jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.1.3
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: 
            diffbot2_control
            diffbot2_description
            diffbot2_robot
          target-ros2-distro: foxy
          vcs-repo-file-url: ""
