name: Colcon build and test

on: [push, pull_request]

jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [dashing, foxy]
        linter: [xmllint, lint_cmake]
    steps:
      - uses: ros-tooling/setup-ros@0.0.25
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          distribution: ${{ matrix.ros_distribution }}
      - uses: ros-tooling/action-ros-ci@0.0.18
        with:
          import-token: ${{ secrets.ROS_CI }}
          id: action_ros_ci_step
          package-name: diffbot2_robot
          target-ros2-distro: ${{ matrix.ros_distribution }}
