name: Ament Lint

on: [push]

jobs:
  ament_lint:
    name: ament_lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [xmllint, lint_cmake]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.0.25
      - uses: ros-tooling/action-ros-lint@master
        with:
          distribution: foxy
          linter: ${{ matrix.linter }}
          package-name: your_package_name
            diffbot2_control
            diffbot2_description
            diffbot2_robot
