name: ROS Lint

on: [push, pull_request]

jobs:
  ament_lint:
    name: build_and_test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [xmllint, lint_cmake]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.0.25
      - uses: ros-tooling/action-ros-lint@master
        with:
          distribution: foxy
          linter: ${{ matrix.linter }}
          package-name: your_package_name
            diffbot2_bringup
            diffbot2_control
            diffbot2_description
            diffbot2_navigation
            diffbot2_perception
            diffbot2_robot
            diffbot2_tests
